### PR TITLE
Edit to categorical data section and the addition of box and whisker plots

### PR DESCRIPTION
**Pull request by campbelle1**
Please let me know if this works and if you have suggestions for changes. Please don't change things without prior discussion.

### CODE REVIEW

**Comment by jesteria** [comment]
Hello! Of course. Thanks for the pull request.

Just looking at what's committed here, I see [three Notebooks added for chapter 8](https://github.com/chicago-cdac/textbook-datascience-1/pull/32/files#diff-9203097d8e822974308fde2378e60b56f97a3c50d0194f382876e070d17704f2). I'm guessing these are/were intended for what's now chapter 9 (data visualization). Were these Notebooks added accidentally? Or are they perhaps intended to replace what's now in chapter 9? (There are of course also changes here to the files currently making up chapter 9.)

Beyond that, just looking over the other changes:

* (Kind of trivial to mention but I also see the empty file `.Rhistory` added. I would think this is not needed for the repository and I can just ensure it's excluded.)

* It's not hugely important but I see the addition of filters to ignore warnings (`warnings.filterwarnings()`). I would hope this isn't necessary for the textbook; though there's not great harm in it either. Of course if there's an ongoing issue relating to this I'd be happy to help with it.

Otherwise of course this looks great. I might hold off on testing it in the textbook just until I know which files are intended.

**Comment by campbelle1** [comment]
Hi Jesse,

Thanks for your reply and attention. The files for chapter 8 was a mistake on my end. Those can be deleted, as we only need the place holder file for that.

Where was the .Rhistory file added? I didn't intend to add that as well and it can be deleted. 

I added a warnings command just for the Categorical data notebook. The other notebooks should be fine I believe.

**Comment by campbelle1** [comment]
Hi Jesse,

Thanks for your reply and attention. The files for chapter 8 was a mistake on my end. Those can be deleted, as we only need the place holder file for that.

Where was the .Rhistory file added? I didn't intend to add that as well and it can be deleted. 

I added a warnings command just for the Categorical data notebook. The other notebooks should be fine I believe.

**Comment by jesteria** [comment]
OK – (as you can see above) – I've committed two changesets, one to remove the .Rhistory file and ignore these in the future, and one to remove those notebooks that were added to the chapter 8 directory.

For the moment you can review [these changesets in this pull request](https://github.com/chicago-cdac/textbook-datascience-1/pull/32/commits).

And if you like you can review [the end-result changes here as well](https://github.com/chicago-cdac/textbook-datascience-1/pull/32/files).

These data visualization notebooks appear nicely compatible with the textbook and build fine. Looks good to me.

I'm curious that we need to filter warnings at all; but, that's fine, certainly there and for now.

I can incorporate this if it looks good to you as well.

**Comment by campbelle1** [comment]
> OK – (as you can see above) – I've committed two changesets, one to remove the .Rhistory file and ignore these in the future, and one to remove those notebooks that were added to the chapter 8 directory.
> 
> For the moment you can review [these changesets in this pull request](https://github.com/chicago-cdac/textbook-datascience-1/pull/32/commits).
> 
> And if you like you can review [the end-result changes here as well](https://github.com/chicago-cdac/textbook-datascience-1/pull/32/files).
> 
> These data visualization notebooks appear nicely compatible with the textbook and build fine. Looks good to me.
> 
> I'm curious that we need to filter warnings at all; but, that's fine, certainly there and for now.
> 
> I can incorporate this if it looks good to you as well.

Looks good to me, thanks!

**Comment by jesteria** [comment]
OK. This work is merged and published: https://ds1.datascience.uchicago.edu/09/data-visualization.html

---

FYI: Since this was pulled from your fork's main branch (`master`), you might just want to re-sync that branch with this repository's before beginning anything new. No need to worry about it but it might help in the future. I've [outlined this for example here](https://github.com/chicago-cdac/textbook-datascience-1/pull/30#issuecomment-1317441093). (Otherwise it can help just to do work in separate branches.) Thanks.

**Pull request merged**
