### PR TITLE
Placeholders

### PR DESCRIPTION
**Pull request by amandakube**
Dan wants placeholders in first two chapters. Also, noticing that there are differences between these two in one of the notebooks in chapter 11. Wasn't able to resolve, hoping you can

### CODE REVIEW

**Comment by jesteria** [comment]
OK. Looking at that notebook in Chapter 11 – did you *want* to change something about it? (I'm guessing that it's not involved in this placeholder work; and, its changes just appear to be in the metadata from Jupyter.)

**Comment by amandakube** [comment]
Yes, exactly. I don't want to change anything

---
Amanda Kube, MS, PhD
Preceptor in Data Science
Data Science Institute
The University of Chicago
5801 S Ellis Ave
Chicago, IL 60637
***@***.***

________________________________

**Comment by jesteria** [comment]
OK sure. I can just revert that one file then and it's all good.

---

FYI: It looks like perhaps the issue is that your fork's main ("master") branch is far out of sync with this repo's. Otherwise this all seems great – you're using branches on your fork, _etc_. I believe if you fix up your fork's `master` branch this will go smoother.

For example in your fork's checkout:

* If you don't have this repository configured:

  ```sh
  git remote add upstream git@github.com:chicago-cdac/textbook-datascience-1.git
  ```

  (…And I'll refer to it as `upstream` regardless.)

* Fetch this repository's changesets:

  ```sh
  git fetch upstream
  ```

* Reset your fork's `master` branch to match that of this repository – (discarding anything in that branch of your fork that's not in this repository!)

  ```sh
  git checkout master
  git reset --hard upstream/master  
  git push --force origin master
  ```

As a result, whereas your fork now says that it's ahead and/or behind this repository's `master` branch, it should then say that it's up-to-date.

image

And I hope that helps!

**Comment by jesteria** [comment]
OK! That took some doing but I believe it's all good now. The end result is of course that this won't change anything in chapter 11 (and won't bring in 40 or so unrelated changesets).

I'll merge it in but if you can please take a look to confirm it looks correct to you.

(And if you're able to clean up your fork that might help a great deal.)

Thanks!

**Pull request merged**
