### PR TITLE
One giant PR

### PR DESCRIPTION
**Pull request by amandakube**
Hi Jesse,

To make editing easier over break, I was building a draft version of the textbook on GithubPages and so people were sending PRs to me. This is all of the edits since the last PR I submitted to you. I fixed all merge conflicts I saw as I went and also put the site through a dead link checker and fixed all dead links but didn't do anything with making code look nicer. I am still hoping to get a chapter from Dan but not sure when that will happen and we need a frozen version of the textbook for class starting tomorrow! Can you merge this and the other PRs on here and create a new release that we freeze to give students and have another working version we can continue adding to?

Thanks so much!
Amanda

### CODE REVIEW

**Comment by jesteria** [comment]
Sounds good to me. Thanks!

---

FYI:

* I removed the `workflow_dispatch` change from the PR – it sounds like this was useful in your fork but I don't believe we need it here. (This repo's builds are triggered by Releases; and, otherwise, we can always build the textbook locally. Though, again, glad you were able to use this feature; and, it looks like perhaps you'd intended to remove this line as well.)
* I wasn't sure for myself about self-attribution within the textbook; but, I see that you've added attribution to my sub-chapter on Lists/Sequences (thanks!). And so I presume I may as well do the same for my chapter on DataFrames.
* Two cells in the Assignments sub-chapter were incorrectly of type "code" rather than "markdown", and as such these threw exceptions and were rendered oddly in the textbook. I switched these to markdown.
* I silenced build errors/warnings due to Notebook cells which purposefully raise exceptions, by assigning those cells the tag: `raises-exception`.
* The build also complained about a few broken internal links which it simply stripped from the end result. (_E.g._, in Arrays Slicing: `[Lists](./1/Lists.ipynb)` was no longer correct; rather, it had to be something like `[Lists](../../1/Lists)`.) These were corrected.

**Comment by amandakube** [comment]
Responses Inline:

- I removed the workflow_dispatch change from the PR – it sounds like this was useful in your fork but I don't believe we need it here. (This repo's builds are triggered by Releases; and, otherwise, we can always build the textbook locally. Though, again, glad you were able to use this feature; and, it looks like perhaps you'd intended to remove this line as well.)

Oh sorry, I thought I removed that before submitting the pull request! Thank you for removing

- I wasn't sure for myself about self-attribution within the textbook; but, I see that you've added attribution to my sub-chapter on Lists/Sequences (thanks!). And so I presume I may as well do the same for my chapter on DataFrames.

Yes, of course!

- Two cells in the Assignments sub-chapter were incorrectly of type "code" rather than "markdown", and as such these threw exceptions and were rendered oddly in the textbook. I switched these to markdown.

Thank you!

- I silenced build errors/warnings due to Notebook cells which purposefully raise exceptions, by assigning those cells the tag: raises-exception.

Great!

- The build also complained about a few broken internal links which it simply stripped from the end result. (E.g., in Arrays Slicing: [Lists](./1/Lists.ipynb) was no longer correct; rather, it had to be something like [Lists](../../1/Lists).) These were corrected.

Huh odd, I thought I fixed all of the broken links. Not sure what happened there

**Comment by amandakube** [comment]
How will the frozen copy and then any subsequent releases for work in progress work? What link can we give students for a frozen copy?

**Comment by jesteria** [comment]
OK: [this is all published](https://ds1.datascience.uchicago.edu/)!

Going forward, and regardless of what's merged to the `master` branch, that main site should remain the place (for students) to see the textbook: `ds1.datascience.uchicago.edu`.

So long as no one creates a Release, the content there won't change.

Any changes to the built site can be reviewed locally (`manage build [--all]`). Beyond that, if there's need for a draft/pre-print/staging website, I imagine this could be accomplished with a fork, (much the way you did in your fork).

Hope that does the trick!

**Pull request merged**
