### PR TITLE
Data Collection Edits

### PR DESCRIPTION
**Pull request by amandakube**
Made some changes to my chapter (Now ch 10, before ch 11)

### CODE REVIEW

**Comment by amandakube** [comment]
Closed by mistake sorry!

**Comment by jesteria** [comment]
FYI: I pushed some minor clean-up to the branch.

**Review by jesteria — CHANGES_REQUESTED** [review]
I can merge this; but, it looks like the Biases section – which was split into a separate section – is also still in the Sampling section (repeated).

**Comment by amandakube** [comment]
Ah, total mistake. I will fix shortly

---
Amanda Kube, MS, PhD
Preceptor in Data Science
Data Science Institute
The University of Chicago
5801 S Ellis Ave
Chicago, IL 60637
***@***.***

________________________________

**Comment by jesteria** [comment]
Cool, I think. Did you mean to close this?

**Pull request closed without merging**
