### PR TITLE
Adding Chapter 11

### PR DESCRIPTION
**Pull request by amandakube**
Adding Chapter 11 for review.

Here are edits to be added to toc to show new chapter
- title: "Data Collection"
  file: 11/ch11intro

  sections:
  - file: 11/01/ch11causality
  - file: 11/02/ch11experiments
  - file: 11/03/ch11sampling

### CODE REVIEW

**Comment by rahimrasool** [comment]
In order to render images on the notebooks, you also need to push the image to the repo and then change the path to the relative path. For eg. for images used in 11/03/ch11sampling, push the images to the same folder and in the notebook just use the image name "image.png" as the path.

**Comment by amandakube** [comment]
Whoops sorry, I thought they needed to go in the images folder and then forgot to change the paths. Should be fixed now!

**Comment by jesteria** [comment]
Hey guys, this really didn't work:

* images (still?) aren't working: [example](https://ds1.datascience.uchicago.edu/11/01/ch11causality.html)
* there's just one Jupyter Notebook – cool – and it's been committed, but it's not included anywhere (neither above in comments nor in the table of contents nor of course in the published textbook)
* though not a huge deal I'm seeing plenty of build warnings

…I think we can get this sorted! Let's do that. Here.

**Comment by rahimrasool** [comment]
Yes, the images weren't running for most of the notebooks (even though the path is correct) and we can work on fixing that. 

The table of contents wasn't committed in this PR. That was my mistake, I missed that out but updated it in the master and submitted a new release 0.2.3

**Comment by jesteria** [comment]
I'm referring to the Notebook in this PR. It's been committed but entirely ignored, no? This PR adds 5 files, and the TOC only considers 4.

**Comment by rahimrasool** [comment]
Alright. It seems that the notebook is redundant since its a combination of all the content in the 3 sub-chapters. @amandakube can confirm this.

**Comment by jesteria** [comment]
Yes, @amandakube, if you could confirm this, and perhaps open a new PR with just the files you'd like to contribute for this chapter, that would be great.

(And we can figure out things like the images there.)

Thanks!

**Comment by amandakube** [comment]
Yes, notebook is how I originally wrote everything. Then, had to split into other files for toc to show sections. Committed the notebook because it may be easiest to read everything for editing reasons. I could make a new pull request, but seems easiest just to delete later? Everything else is needed. Not sure why images wouldn't work. Paths are correct and images are all in correct files. I also thought we weren't supposed to push our toc changes and just have one of you make edits to avoid merge conflicts? So I just commented the toc changes that should be added.

**Comment by jesteria** [comment]
OK, great. Thanks for confirming. That's fine, I'll take care of this in a branch, then.

**Comment by jesteria** [comment]
See: #16

**Pull request merged**
