### PR TITLE
Change to toc ch3

### PR DESCRIPTION
**Pull request by amandakube**
Removed data8 material, changed section names, added placeholders for people to work off of to, hopefully, reduce merge conflicts as we all write the chapter together

### CODE REVIEW

**Comment by jesteria** [comment]
To reiterate, there has never been material in this repository belonging to Data-8. (I'm guessing that's not news. I just want to be clear. [Here is where this was last discussed in full](https://github.com/chicago-cdac/textbook-datascience-1/pull/25#issuecomment-1301302641).)

Rather, these materials were put together from a BSD-licensed demo.

It sounds like the team has plans for new content to take this place, and perhaps even regardless of the above. Sounds good.

I'll add that at least a couple of these programming chapters I wrote from scratch for the textbook, (in addition to the chapter on DataFrames), way back in 2020. Perhaps these are no longer needed. But they are particularly distinct from the above:

* [added programming chapter 03/3/3: Sequences](https://github.com/chicago-cdac/textbook-datascience-1/commit/5b74180e3b3117bbadd5dbb024999403611b856e#diff-f677bd13f9dfc5fc0818bd16d3d458e71782067be5a2c659f86ea6ff4a61722b)
* [added new programming chapter -- 3.6: Functions](https://github.com/chicago-cdac/textbook-datascience-1/commit/af64ac6e7161c0eb096f5f982ecd49440bc28293#diff-fc014db90f1c7f6b083d432b5441903928f33539af8439e3cd5307995adff169)

**Comment by amandakube** [comment]
What I meant about the data8 material is that it is in data8 (not necessarily belonging to). I think the consensus is that we don't want to include any information that is also in their textbook (including the demo material). I am sorry if I also removed content that you wrote, I was told it was all the same and honestly didn't check. Please add any of your material back to this section and we can rewrite the ones that were replicated. We also wanted our section names to be distinct from those used in data8 which is why we changed some of those as well. Maybe we can reformat some of what you had into these new sections? For example, including call-expression (built-in functions) in the same section as functions in general. Or moving some of the sequences material into the data structures chapter and keeping some in a new section for dictionaries. Would this be ok with you? If so, you are welcome to do that so that it is written the way you would like.

**Comment by jesteria** [comment]
Sure, understood.

And, to be sure, what I'd written (way back when) was done with an older conception of the chapter and textbook in mind. I hope it can still be of use, but I'd certainly understand if it weren't or if it had to be adapted.

I'll restore what I'd written. And it sounds like we can just see what there is to do with it.

**Comment by jesteria** [comment]
OK:

* It looks like your fork is fine; nonetheless, this branch contained a stale commit that was preventing a merge. (It is generally best to delete branches once they've been merged, and perhaps that was at issue.) Anyway, I just dropped that duplicative/stale changeset and it's good now.
* I added the old-but-non-demo Sequences page back in. Perhaps this will be of use, perhaps not! (I ultimately elected to let the Functions one drop – there wasn't much in there, and it looks like the group intends to do a more thorough job on the topic.)
* It also looks like there are typos in the TOC. Sorry for all the updates but I can just tweak those now….

**Review by jesteria — APPROVED** [review]

**Pull request merged**
