### PR TITLE
Removed all the placeholder content and revised TOC to reflect that

### PR DESCRIPTION
**Pull request by wltrimbl**

### CODE REVIEW

**Comment by jesteria** [comment]
Hello! Thanks. So were you given a list of "placeholder" content to remove? Or is this perhaps your initiative? A number of these pages on programming I adapted, back in 2020, from BSD-licensed work, (and I added my own).

…Now that we're (finally) moving forward with this, perhaps these pages are not entirely wanted in the textbook?

**Comment by wltrimbl** [comment]
Initiative?  Some of our new chapters are good enough we want to start sharing them with students soon.

All of the removed content is identical to data8.  All of the original content I preserved.  Some of the cdac-specific content was indexed by google and some was not.

data8 is (CC BY-NC-ND 4.0), the most restrictive clause being no derivatives.

**Comment by jesteria** [comment]
That's great.

Yes, of course; but my understanding is that the Data-8 textbook itself
republished that particular content from the Jupyter Book project, which
originally published it years ago under a BSD license. (BSD-licensed
content may be republished under more restrictive licensing.) Nothing
currently in this textbook came from Data-8; it came from us and in part
from Jupyter Book.

(If we don't want it of course we shouldn't keep it. My understanding,
albeit from quite a while ago, was merely that it was wanted.)

**Comment by wltrimbl** [comment]
I was afraid you were going to tell me the content had a longer backstory.

Since my purpose was entirely to remove content I thought was not properly licensed, you can close this PR without merging it.

**Comment by jesteria** [comment]
For posterity it is worth noting with precision: some content in this repository originally came from the Jupyter Book demo – released along with Jupyter Book under its BSD license.

And at least some of this content is likely of use. (For that reason you'll also find some of it in the Data-8 textbook.) We'll see. Regardless, it is properly licensed.

You may refer to the Jupyter Book repository – around the time that that library was used to initiate this repository – to confirm [the presence of such files there](https://github.com/executablebooks/jupyter-book/tree/e54a0e045a2e1d0e61c346a9289cc0410dd35bd4/jupyter_book/book_template/content) (as well as its [BSD license](https://github.com/executablebooks/jupyter-book/blob/e54a0e045a2e1d0e61c346a9289cc0410dd35bd4/LICENSE)).

**Pull request closed without merging**
